# Используем официальный образ Python
FROM python:3.9-slim

# Устанавливаем рабочую директорию в контейнере
WORKDIR /app

# Копируем файл requirements.txt в контейнер
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь проект в контейнер
COPY . .

# Устанавливаем Daphne
RUN pip install daphne

# Указываем команду для запуска с Daphne
CMD ["daphne", "config.asgi:application", "--bind", "0.0.0.0", "--port", "8000"]
