# Используем официальный Python-образ
FROM python:3.11-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Обновляем пакеты и устанавливаем системные зависимости
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    gcc \
    netcat-openbsd \
    curl \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# Копируем только файл зависимостей сначала (для кэширования pip install)
COPY requirements.txt .

# Устанавливаем Python-зависимости
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Копируем остальной проект
COPY . .

# Даем права на выполнение entrypoint.sh
RUN chmod +x ./entrypoint.sh

# Указываем, что контейнер будет использовать порт 8000
EXPOSE 8000

# Команда запуска
CMD ["./entrypoint.sh"]
