# Generated by Django 5.0.6 on 2025-03-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='quality_type',
            field=models.CharField(choices=[('perfect', 'Отличное'), ('good', 'Хорошее'), ('working', 'Рабочее')], max_length=20, unique=True),
        ),
    ]
