# Generated by Django 5.1.6 on 2025-04-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='processing', max_length=10),
        ),
    ]
