# Generated by Django 5.1.6 on 2025-05-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='quality_type',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('not_bad', 'Not Bad')], max_length=20, unique=True),
        ),
    ]
