# Generated by Django 4.2.17 on 2025-05-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_quality_quality_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='quality_type',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
