<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-04-13 06:35
=======
# Generated by Django 5.1.6 on 2025-04-11 10:57
>>>>>>> 696a8b2946a8e8a1248365c0d91ef1e1fb9dbd7e

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('products', '0004_product_average_rating'),
=======
        ('products', '0005_product_views'),
>>>>>>> 696a8b2946a8e8a1248365c0d91ef1e1fb9dbd7e
        ('reviews', '0003_alter_review_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'product')},
        ),
    ]
